=== UO294013/f1/xml/circuito.dtd
<!ELEMENT circuitos (circuito+)>
<!ELEMENT circuito (vueltas, anchura_media, fecha2024, hora_inicio_españa, referencias, fotos, videos, coordenadas, tramos)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT anchura_media (#PCDATA)>
<!ELEMENT fecha2024 (#PCDATA)>
<!ELEMENT hora_inicio_españa (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT referencias (referencia*)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT fotos (foto*)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT videos (video*)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT coordenadas (coordenada)>
<!ELEMENT coordenada (#PCDATA)>
<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (coordenada)>
<!ATTLIST circuito 
    nombre CDATA #REQUIRED
	longitud_circuito CDATA #REQUIRED
    localidad CDATA #REQUIRED
	pais CDATA #REQUIRED>
<!ATTLIST coordenada 
	longitud CDATA #REQUIRED
    latitud CDATA #REQUIRED
    altitud CDATA #REQUIRED>
<!ATTLIST tramo 
	distancia CDATA #REQUIRED
    numero_sector CDATA #REQUIRED>

=== UO294013/f1/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuitos SYSTEM "circuito.dtd">
<circuitos>
    <circuito nombre="Spa-Francorchamps" longitud_circuito="7004" localidad="Spa-Francorchamps" pais="Bélgica">
        <vueltas>44</vueltas>
        <anchura_media>10</anchura_media>
        <fecha2024>2024-07-28</fecha2024>
        <hora_inicio_españa>15:00:00</hora_inicio_españa>
        <referencias>
            <referencia>https://es.wikipedia.org/wiki/Circuito_de_Spa-Francorchamps</referencia>
            <referencia>https://circuitomotor.com/belgica/circuito-de-spa-francorchamps/</referencia>
            <referencia>https://motorsporttickets.com/blog/spa-francorchamps-track-guide/</referencia>
            <referencia>https://lebalap.academy/f1/spa-francorchamps/</referencia>
            <referencia>https://desdelapelouse.wordpress.com/2011/08/27/circuito-de-spa-francorchamps/#:~:text=Longitud%3A%207%2C004%20km.de%20la%20pista%3A%2010%20m</referencia>
        </referencias>
        <fotos>
            <foto>spa.jpg</foto>
            <foto>spa2.jpg</foto>
            <foto>spa-esquema.png</foto>
        </fotos>
    <videos>
        <video>onboard_spa.mp4</video>
    </videos>
    <coordenadas>
        <coordenada longitud="5.9651156" latitud="50.4441123" altitud="415.53"></coordenada> 
    </coordenadas>
    <tramos> <!-- La distancia se mide desde el tramo anterior hasta el punto concreto -->
        <tramo distancia="295.35" numero_sector="1">
            <coordenada longitud="5.9651656" latitud="50.4440586" altitud="415.27"></coordenada>
        </tramo>
        <tramo distancia="262.52" numero_sector="1">
            <coordenada longitud="5.9633485" latitud="50.4461178" altitud="422.47"></coordenada>
        </tramo>
        <tramo distancia="6.32" numero_sector="1">
            <coordenada longitud="5.9633572" latitud="50.4461773" altitud="423.17"></coordenada>
        </tramo>
        <tramo distancia="7.39" numero_sector="1">
            <coordenada longitud="5.9634334" latitud="50.4462281" altitud="423.04"></coordenada>
        </tramo>
        <tramo distancia="8.69" numero_sector="1">
            <coordenada longitud="5.9635438" latitud="50.4462588" altitud="422.37"></coordenada>
        </tramo>
        <tramo distancia="16.50" numero_sector="1">
            <coordenada longitud="5.9637578" latitud="50.4462281" altitud="421.49"></coordenada>
        </tramo>
        <tramo distancia="149.13" numero_sector="1">
            <coordenada longitud="5.9656389" latitud="50.4456188" altitud="412.21"></coordenada>
        </tramo>
        <tramo distancia="58.59" numero_sector="1">
            <coordenada longitud="5.9663554" latitud="50.4453425" altitud="408.80"></coordenada>
        </tramo>
        <tramo distancia="74.10" numero_sector="1">
            <coordenada longitud="5.9671686" latitud="50.4449236" altitud="404.96"></coordenada>
        </tramo>
        <tramo distancia="53.87" numero_sector="1">
            <coordenada longitud="5.9677090" latitud="50.4445833" altitud="402.66"></coordenada>
        </tramo>
        <tramo distancia="302.09" numero_sector="1">
            <coordenada longitud="5.9704798" latitud="50.4425167" altitud="388.64"></coordenada>
        </tramo>
        <tramo distancia="66.62" numero_sector="1">
            <coordenada longitud="5.9712765" latitud="50.4421967" altitud="391.64"></coordenada>
        </tramo>
        <tramo distancia="27.10" numero_sector="1">
            <coordenada longitud="5.9715374" latitud="50.4420297" altitud="395.36"></coordenada>
        </tramo>
        <tramo distancia="35.73" numero_sector="1">
            <coordenada longitud="5.9634334" latitud="50.4462281" altitud="400.04"></coordenada>
        </tramo>
        <tramo distancia="90.21" numero_sector="1">
            <coordenada longitud="5.9720595" latitud="50.4409616" altitud="412.55"></coordenada>
        </tramo>
        <tramo distancia="334.33" numero_sector="1">
            <coordenada longitud="5.9744455" latitud="50.4383972" altitud="426.30"></coordenada>
        </tramo>
        <tramo distancia="796.59" numero_sector="2">
            <coordenada longitud="5.9775547" latitud="50.4315271" altitud="463.24"></coordenada>
        </tramo>
        <tramo distancia="21.84" numero_sector="2">
            <coordenada longitud="5.9775058" latitud="50.4313368" altitud="462.97"></coordenada>
        </tramo>
        <tramo distancia="25.24" numero_sector="2">
            <coordenada longitud="5.9773164" latitud="50.4311736" altitud="463.69"></coordenada>
        </tramo>
        <tramo distancia="34.96" numero_sector="2">
            <coordenada longitud="5.9769110" latitud="50.4310110" altitud="465.04"></coordenada>
        </tramo>
        <tramo distancia="36.40" numero_sector="2">
            <coordenada longitud="5.9766764" latitud="50.4307241" altitud="466.14"></coordenada>
        </tramo>
        <tramo distancia="122.34" numero_sector="2">
            <coordenada longitud="5.9770346" latitud="50.4297260" altitud="468.00"></coordenada>
        </tramo>
        <tramo distancia="47.01" numero_sector="2">
            <coordenada longitud="5.9768467" latitud="50.4293408" altitud="467.01"></coordenada>
        </tramo>
        <tramo distancia="316.41" numero_sector="2">
            <coordenada longitud="5.9732194" latitud="50.4277199" altitud="454.29"></coordenada>
        </tramo>
        <tramo distancia="22.33" numero_sector="2">
            <coordenada longitud="5.9729164" latitud="50.4276692" altitud="452.90"></coordenada>
        </tramo>
        <tramo distancia="33.42" numero_sector="2">
            <coordenada longitud="5.9725196" latitud="50.4277518" altitud="450.93"></coordenada>
        </tramo>
        <tramo distancia="26.48" numero_sector="2">
            <coordenada longitud="5.9722659" latitud="50.4279243" altitud="449.43"></coordenada>
        </tramo>
        <tramo distancia="38.13" numero_sector="2">
            <coordenada longitud="5.9722161" latitud="50.4282333" altitud="446.22"></coordenada>
        </tramo>
        <tramo distancia="42.49" numero_sector="2">
            <coordenada longitud="5.9725398" latitud="50.4285104" altitud="443.68"></coordenada>
        </tramo>
        <tramo distancia="141.11" numero_sector="2">
            <coordenada longitud="5.9741998" latitud="50.4292070" altitud="433.19"></coordenada>
        </tramo>
        <tramo distancia="36.96" numero_sector="2">
            <coordenada longitud="5.9743306" latitud="50.4294994" altitud="431.61"></coordenada>
        </tramo>
        <tramo distancia="190.70" numero_sector="2">
            <coordenada longitud="5.9735299" latitud="50.4311381" altitud="419.89"></coordenada>
        </tramo>
        <tramo distancia="279.19" numero_sector="2">
            <coordenada longitud="5.9728193" latitud="50.4335970" altitud="399.49"></coordenada>
        </tramo>
        <tramo distancia="40.02" numero_sector="2">
            <coordenada longitud="5.9725228" latitud="50.4338999" altitud="395.83"></coordenada>
        </tramo>
        <tramo distancia="49.10" numero_sector="2">
            <coordenada longitud="5.9720336" latitud="50.4341367" altitud="392.69"></coordenada>
        </tramo>
        <tramo distancia="90.90" numero_sector="2">
            <coordenada longitud="5.9707956" latitud="50.4342342" altitud="388.07"></coordenada>
        </tramo>
        <tramo distancia="45.76" numero_sector="2">
            <coordenada longitud="5.9701690" latitud="50.4341840" altitud="385.24"></coordenada>
        </tramo>
        <tramo distancia="37.41" numero_sector="2">
            <coordenada longitud="5.9696986" latitud="50.4340493" altitud="381.31"></coordenada>
        </tramo>
        <tramo distancia="42.70" numero_sector="2">
            <coordenada longitud="5.9692410" latitud="50.4338116" altitud="378.88"></coordenada>
        </tramo>
        <tramo distancia="62.48" numero_sector="2">
            <coordenada longitud="5.9688025" latitud="50.4333865" altitud="376.88"></coordenada>
        </tramo>
        <tramo distancia="310.25" numero_sector="2">
            <coordenada longitud="5.9671755" latitud="50.4307878" altitud="374.74"></coordenada>
        </tramo>
        <tramo distancia="31.72" numero_sector="2">
            <coordenada longitud="5.9668982" latitud="50.4305575" altitud="375.05"></coordenada>
        </tramo>
        <tramo distancia="34.44" numero_sector="2">
            <coordenada longitud="5.9664840" latitud="50.4304178" altitud="375.92"></coordenada>
        </tramo>
        <tramo distancia="34.36" numero_sector="2">
            <coordenada longitud="5.9660193" latitud="50.4304077" altitud="376.14"></coordenada>
        </tramo>
        <tramo distancia="39.94" numero_sector="2">
            <coordenada longitud="5.9655167" latitud="50.4305290" altitud="376.60"></coordenada>
        </tramo>
        <tramo distancia="44.44" numero_sector="2">
            <coordenada longitud="5.9649707" latitud="50.4307076" altitud="375.91"></coordenada>
        </tramo>
        <tramo distancia="41.52" numero_sector="2">
            <coordenada longitud="5.9644189" latitud="50.4306837" altitud="375.29"></coordenada>
        </tramo>
        <tramo distancia="48.98" numero_sector="2">
            <coordenada longitud="5.9639192" latitud="50.4304453" altitud="374.74"></coordenada>
        </tramo>
        <tramo distancia="205.14" numero_sector="2">
            <coordenada longitud="5.9623892" latitud="50.4289034" altitud="370.91"></coordenada>
        </tramo>
        <tramo distancia="26.30" numero_sector="2">
            <coordenada longitud="5.9620841" latitud="50.4287750" altitud="369.70"></coordenada>
        </tramo>
        <tramo distancia="26.84" numero_sector="2">
